spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    time-zone: Asia/Ho_Chi_Minh
app:
  jwt:
    secret: my-super-secret-key-which-is-at-least-32-chars-long
    issuer: "restaurant-system"
    access-expiration-ms: 900000  # 1 ng√†y
    refresh-expiration-ms: 1209600000
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176

vnpay:
  tmn-code: "WE4MRD4Y"
  hash-secret: "RX519LB7DLDVURX06QTLB6KVL99UP4IU"
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "https://glowfly-shredless-iluminada.ngrok-free.dev/invoices/vnpay-return"
  # 
